# Generated by Django 4.2.4 on 2023-08-11 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medibot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_availability',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
